### ISSUE TITLE
Clean up & refactor

### ISSUE THREAD

**Issue by jooskim** [jooskim/vic#6]
**User Statement**
As a developer I want to ensure highly legible, maintainable and reusable code for the Create VCH wizard.

**Acceptance Criteria:**
- [ ] Code needs to be properly commented with constants moved into their appropriate place multiple/ongoing
- [ ] Redundant logics could be consolidated into a single function multiple/ongoing
- [ ] Implement cache for some methods in the service multiple/ongoing
- [X] move global imports to app.module #43
- [ ] move common functionality (create-vch-wizard.service/vm.constants/vm.interface) to shared/constants #37
- [ ] change #step1 etc to things like #nameStep on form steps #41
- [ ] common functions (e.g resizeToParentFrame) util files #36 
- [ ] cleanup folder structure #42
- [ ] create baseForm class to abstract common form functions #40
- [ ] implement dataModels and viewModels #39
- [ ] extract error and status messages into locale file #38

**Comment by jak-atx** [comment]
Leaving these as todos here for now. These may be broken out into individual tasks as necessary.

- have single module for vic plugin (rather than one per component)

- create baseForm class to abstract common form functions

- implement dataModels and viewModels

- extract error and status messages into locale file
